### ISSUE TITLE
Tables too wide on answer sidebar

### ISSUE THREAD

**Issue by nickdavis** [nickdavis/cmaexamacademy.com#1]
![table goes too wide in sidebar](https://user-images.githubusercontent.com/1030574/66039920-13713580-e50e-11e9-99dd-b56c154d2d08.png)

Reported by student (s.abbasmadani at gmail dot com) via Nathan, 1 Oct 2019

**Comment by nickdavis** [comment]
Example of this is Question 30708, found under P1SA2

**Comment by nickdavis** [comment]
Not sure how best to handle within the current design, as even if we squeezed the fourth column to fit (in the above) example, there are still another two we need to accommodate.

**Comment by nickdavis** [comment]
Discussed with @nathanliao, we will try increasing the answer sidebar for now.

Another option to consider for the future is putting the answers below the question.

**Comment by nickdavis** [comment]
Just thinking out loud on this, the width of the page is already 'maxxed out' for the current design when the answer sidebar is showing, so increasing the answer width means shrinking the question width.

We might get away with a little bit, but if we do it too much we'll end up with the same issue (not even width) for the question column as well.

I'll experiment with it and see if I can come up something that strikes the right balance.

**Comment by nickdavis** [comment]
I've tried a lot of different combinations and I think the only option (without moving the answer above or below) is making the columns 50 / 50. (I also decreased the table font size a little bit).

(This should also ensure that if there is also a table in the question text, it will fit too).

See example screenshot:

<img width="1087" alt="Screenshot 2019-10-02 at 22 06 55" src="https://user-images.githubusercontent.com/1030574/66083056-7214ce80-e563-11e9-9ca5-83ba98658a09.png">

@cmaexamacademy - what do you think? (would you want the buttons to sit below the answer sidebar also?)

**Comment by cmaexamacademy** [comment]
@nickdavis it looks better for sure. wonder when the question itself has a table, will it still look good. 

The buttons can remain below the question, that's fine.

**Comment by nickdavis** [comment]
> wonder when the question itself has a table, will it still look good.
Yes, that was my worry too. I guess if they're 50 / 50 and we keep tables to max 6 columns (how realistic?) it should just about be OK.

I guess I'll try this way for now and we can always come back to this again.

**Comment by nickdavis** [comment]
This has been done, as discussed, and pushed to live.

I will close this for now but feel free to re-open this issue if any further tweaks (or a different approach) is needed.
