### ISSUE TITLE
Essays Picker List

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#10]
@nickdavis is it possible to update the number of essays on the picker list shown attached? Ideally 1, 2, 4 and 6 would be perfect. 
<img width="642" alt="Screen Shot 2019-10-02 at 5 20 43 PM" src="https://user-images.githubusercontent.com/56087053/66090658-3ebd4a00-e539-11e9-85a9-e1af9670ec4f.png">

**Comment by nickdavis** [comment]
Absolutely. Will do today.

**Comment by nickdavis** [comment]
Done and pushed to live site.

<img width="648" alt="Screenshot 2019-10-03 at 11 51 38" src="https://user-images.githubusercontent.com/1030574/66121056-30703c00-e5d4-11e9-9959-4a895c279511.png">
