### ISSUE TITLE
Add a title to Review / Analytics pages

### ISSUE THREAD

**Issue by nickdavis** [nickdavis/cmaexamacademy.com#13]
There was a request, some while back, to add a title to Review / Analytics pages.

I started looking at it, but I realised the title would quickly be lost upon scroll for many people.

I thought then that a better way might be to highlight the current page being viewed in the secondary nav, as a subtle reminder to people and also serving the purpose of a title, see screenshots below.

<img width="278" alt="Screenshot 2019-10-04 at 14 22 20" src="https://user-images.githubusercontent.com/1030574/66210736-6f74bf00-e6b2-11e9-9eb2-8b735f1ead3a.png">
<img width="289" alt="Screenshot 2019-10-04 at 14 22 10" src="https://user-images.githubusercontent.com/1030574/66210737-6f74bf00-e6b2-11e9-8815-a30ae013f204.png">
<img width="301" alt="Screenshot 2019-10-04 at 14 21 59" src="https://user-images.githubusercontent.com/1030574/66210738-6f74bf00-e6b2-11e9-835d-81ccd2d3d68d.png">

**Comment by nickdavis** [comment]
Pushed to live site. Let me know if you want to amend or revisit.

**Comment by cmaexamacademy** [comment]
@nickdavis this looks great! Much better than having a title. Well done.
