### ISSUE TITLE
Font color on main buttons

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#14]
Hey @nickdavis I've gotten several emails from students who got confused about the Essay report button. It's super hard to read and didn't realize it was there at first. Is there a way to make the font color white so it complete stands out and shown as an option to click on? 
<img width="598" alt="Screen Shot 2019-10-04 at 5 18 49 PM" src="https://user-images.githubusercontent.com/56087053/66246714-19604580-e6cb-11e9-9819-839c21909e73.png">

**Comment by nickdavis** [comment]
No problem. This was based on the original Sketch design, but is a simple change.

<img width="422" alt="Screenshot 2019-10-06 at 23 37 59" src="https://user-images.githubusercontent.com/1030574/66277162-5aef1d00-e892-11e9-8cdc-4bdb54e12ed0.png">

Have pushed up to live.

(Let me know if you want the same treatment for the CMA PART 1 / CMA PART 2 tabs for consistency too).

**Comment by cmaexamacademy** [comment]
Thank you. Yes let’s please do the same with the part buttons at the top. Great idea. 

Thank you,

Nathan Liao, CMA | CMA Coach
www.cmaexamacademy.com
PO BOX 124575
San Diego, CA 92112

--- original message ---
> Sun, Oct 6 at 3:47 PM, <notifications@github.com> wrote:


> Closed #14.

> —

> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by nickdavis** [comment]
No problem, have done

**Comment by cmaexamacademy** [comment]
@nickdavis would you mind doing this update to the exam button? 
<img width="483" alt="Screen Shot 2019-10-07 at 9 58 47 PM" src="https://user-images.githubusercontent.com/56087053/66368596-a9152680-e94d-11e9-8e16-37ee5fdd8563.png">

**Comment by nickdavis** [comment]
Done
