### ISSUE TITLE
Wrong Questions in Practice Exams

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#15]
@nickdavis I sent you a quick whatsapp on this but opening an issue here as well. 

I have several students saying that during their Section A practice exam in Part One, they are getting questions from other sections, as many as half of their questions belong to a different section. Could you please verify that the programming is set to pull only questions by section? 

I asked my team to verify their data entry as well in the meantime, but would like confirmation from your end as well. Thank you.

**Comment by cmaexamacademy** [comment]
My team checked the questions and they are all correct in Section A, @nickdavis . Just an FYI. Thanks

**Comment by nickdavis** [comment]
@cmaexamacademy good catch, this was a bug that was introduced Thursday(?), when I did the merge with the theme to allow the same header / menu, now resolved

**Comment by cmaexamacademy** [comment]
Nick,


Ok glad you found the issue. I’ll let everyone know to resume their exams. 

Thank you,

Nathan Liao, CMA | CMA Coach
www.cmaexamacademy.com
PO BOX 124575
San Diego, CA 92112

--- original message ---
> Sun, Oct 6 at 2:18 PM, <notifications@github.com> wrote:


> Closed #15.

> —

> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by cmaexamacademy** [comment]
Nick, just verifying that this was fixed for both parts, not just part 1? I’m sure you have but want to double check. Thanks. 

Thank you,

Nathan Liao, CMA | CMA Coach
www.cmaexamacademy.com
PO BOX 124575
San Diego, CA 92112

--- original message ---
> Sun, Oct 6 at 2:30 PM, <nathan@cmaexamacademy.com> wrote:


> Nick,


> Ok glad you found the issue. I’ll let everyone know to resume their exams. 



> Thank you,


> Nathan Liao, CMA | CMA Coach

> www.cmaexamacademy.com

> PO BOX 124575
> San Diego, CA 92112


>>> Sun, Oct 6 at 2:18 PM, <notifications@github.com> wrote:


>>> Closed #15.

>>> —

>>> You are receiving this because you were mentioned.

>>> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by cmaexamacademy** [comment]
@nickdavis Students are reporting that they are getting the same questions repeated and not seeing new questions. Can you please double check this urgently please.

**Comment by nickdavis** [comment]
> Nick, just verifying that this was fixed for both parts, not just part 1? I’m sure you have but want to double check. Thanks.

Both parts run on exactly the same code, so as long as the data (question) entry is fine for both, a code fix in one place will also be a code fix in another

**Comment by nickdavis** [comment]
> Students are reporting that they are getting the same questions repeated and not seeing new questions. Can you please double check this urgently please.

After some investigation, first of all, I assume we're both talking about the following:

1. Student chooses a section / topic from the Dashboard topics list.
2. Student clicks Practice, then selects New as the Question Type
3. Student completes the Session
4. Student completes more Sessions of the same section / topic, selecting New every time.
5. Eventually, of course, the Student should run out of 'New' questions for that section / topic
6. In these cases, the software should fallback to 'All' questions with a warning message to the Student explaining them why it couldn't show them 'New' questions instead

Assuming this is what we're both talking about, it looks like step 6 is partially failing.

I tested this just now and what happens at the moment:

- If I take a 5 Question 'New' session from a topic with only 6 questions, it correctly shows me 5 questions the first time
- If I try to take a 5 Question 'New' session from the same 6 question topic again, it correctly shows me only 1 question with a warning, see screenshot
<img width="1051" alt="Screenshot 2019-10-07 at 20 23 49" src="https://user-images.githubusercontent.com/1030574/66344483-efff1e00-e945-11e9-8b14-dbaf180f1dd3.png">
- So far so good. However, if I then take another 'New' session from the same topic again (0 new questions available to be shown), it shows me 5 'All' questions, which is correct. **However this time it doesn't show me the yellow warning banner at the top, which is not correct**

Therefore what is failing is the warning in that final scenario, which is what I will look at.  @cmaexamacademy : **If that is not the case or you're seeing a different issue please let me know.**

(NB. Although a similar part of the software, this is unrelated - and a separate bug - to the one that was originally reported above so I may move this to a separate ticket).

**Comment by cmaexamacademy** [comment]
@nickdavis khaled_ibrahim2007 khaledsabateen

**Comment by nickdavis** [comment]
Making a note that we discussed yesterday (8 Oct) and the issue was a student was saying that they were getting the same questions repeated within a single session. Unfortunately we don't know the exact session id at this stage, however Nathan believes the user is one of either  `khaled_ibrahim2007` or `khaledsabateen` and it was a recently taken 50 question session.

If we can't deduce from that we will go back to the student to request more information and hopefully get the session id that way.

**Comment by nickdavis** [comment]
I've gone through `khaledsabateen`'s recent MCQ sessions from yesterday (and also one this morning).

It's quite time consuming but I've checked the raw data and there are no repeating exercises (questions) in any of them that I can see, including the prime candidate which was 50 MCQ session generated yesterday (session id 34072).

I've copied the session IDs that I've checked below for my own future reference.

- 34413 (generated after we spoke)
- 34165
- **34072 (50 MCQs)**
- 34046
- 34004
- 33994

**Comment by nickdavis** [comment]
@cmaexamacademy 

There's not much more I can do at this point, but If he believes that he finds a repeating question in a future session, if he can do as follows:

## 1: try to identify the Session, he's in

During or immediately after the session he should be able to get the session ID from the current URL in his browser. Either during a session, like so:

<img width="527" alt="Screenshot 2019-10-08 at 11 57 06" src="https://user-images.githubusercontent.com/1030574/66390555-d51ebf00-e9c2-11e9-97b8-9fcd171ab0ef.png">

Or on the session result page:

<img width="518" alt="Screenshot 2019-10-08 at 11 59 14" src="https://user-images.githubusercontent.com/1030574/66390703-1d3de180-e9c3-11e9-913b-4bb85c5c4b3a.png">

If he's in a session, but the browser does not show a session id, he should copy the current URL and paste it somewhere else (a text file, email etc) and the session id should be revealed then.

## 2. Send us the repeating question id / ids

If he's still on the particular question / questions he believes are repeating. He can copy the relevant question id from the bottom right of the question text area.

<img width="842" alt="Screenshot 2019-10-08 at 12 01 57" src="https://user-images.githubusercontent.com/1030574/66390847-760d7a00-e9c3-11e9-9b9a-94738f2ae547.png">

**Comment by nickdavis** [comment]
The only other likely thing I can think of is if the same question text / answer got entered twice in the database (so it exists but with two different IDs). This could cause a repeating question in a session, because the test bank would believe it to be two different questions (which technically it would be).

If that is the case, getting the question id/ids and the session id would help us track that down. Otherwise, if it's an issue with how the session got generated, getting the session id would let me dig into it further.

**Comment by nickdavis** [comment]
Closed, pending further feedback.
