### ISSUE TITLE
Add 'i' icon option to Analytics table header columns (Correct / Incorrect etc)

### ISSUE THREAD

**Issue by nickdavis** [nickdavis/cmaexamacademy.com#17]
(From Nathan, via Workflowy)

**Comment by nickdavis** [comment]
@cmaexamacademy 

Assuming you still want this, wanted to confirm the position of the tooltip?

It's easy enough to add but the situation is slightly different from our Dashboard / sidebar tooltips which have a lot of space around them.

Looking at our Analytics table, screenshot below, we could add the tooltip icon perhaps just above Correct / Incorrect.

<img width="951" alt="Screenshot 2019-10-07 at 17 51 19" src="https://user-images.githubusercontent.com/1030574/66331933-870aac80-e92b-11e9-851e-86995f00d2d7.png">

On reflection though, I'm thinking:

- Might look a bit squashed (and break the flow of the rest of the design)
- It would also potentially be repeated at the top of every section

**Comment by cmaexamacademy** [comment]
@nickdavis I was thinking that we could just add one icon to the top right hand corner of the entire section. This would still be the same as we do with other sections. I would just have to explain what everything means in on big box broken into paragraphs. Thoughts?

**Comment by nickdavis** [comment]
Yes, that might work. I'll take a look.

**Comment by nickdavis** [comment]
Added. Example screenshot from my local version:

<img width="374" alt="Screenshot 2019-10-08 at 11 07 15" src="https://user-images.githubusercontent.com/1030574/66387422-d7314f80-e9bb-11e9-8ec8-f786661cff8c.png">

To add to the live site, you will need to add some text to the `Analytics (Table)` field on the following page: https://cmaexamacademy.com/wp-admin/admin.php?page=acf-options-test-bank

**The tooltips also now support line breaks too**, if you want to break things up a bit.

**Comment by cmaexamacademy** [comment]
@nickdavis I added text to this. Can you please align it left? It's center now and doesn't look good. 

Also can you verify that the explanation is accurate? Thanks

**Comment by cmaexamacademy** [comment]
@nickdavis I think we should also add an "i" to these two boxes. We can use the PassRate one from the main dashboard here, plus a new one for the timer. Thoughts? 

<img width="537" alt="Screen Shot 2019-10-08 at 5 24 48 PM" src="https://user-images.githubusercontent.com/56087053/66442679-9273db80-e9f0-11e9-9331-406dea43417e.png">

**Comment by cmaexamacademy** [comment]
@nickdavis scratch the "align left" request. It looks fine when I add a row space to each one.

**Comment by nickdavis** [comment]
> Also can you verify that the explanation is accurate? Thanks

@cmaexamacademy I didn't understand this question. Let me know if still an issue.

**Comment by nickdavis** [comment]
I've edited slightly and updated the live site.

Have put the original text and new text below for future reference.

## Original
```
Total = total questions.

Correct = number of questions answered correctly in your most recent practice exam.

Incorrect = number of questions answered incorrectly in your most recent practice exam.

Not Seen = number of questions not seen in a practice exam yet.

Correct = percentage of questions answered correctly. Correct / Total 

Attempts = the number of practice exams for a particular section and/or topic.
```

## Revised
```
Total = total questions.

Correct = number of questions answered correctly in your most recent practice exams for this section/topic.

Incorrect = number of questions answered incorrectly in your most recent practice exams for this section/topic.

Not Seen = number of questions not seen in a practice exam yet.

Correct = percentage of questions answered correctly. Correct / Total 

Attempts = the total number of question attempts for a particular section and/or topic.
```

**Comment by nickdavis** [comment]
Added tooltip to Analytics (PassRate).

Will look at Total time next.

**Comment by nickdavis** [comment]
Added `Total time` tooltip

Some text needs to be added first to `Analytics (Total Time)` at https://cmaexamacademy.com/wp-admin/admin.php?page=acf-options-test-bank

**Comment by cmaexamacademy** [comment]
@nickdavis how would you describe this timer? "Total time tooltip"

"Total time spent in the test bank" is what comes to mind but could be explained better I think.

**Comment by nickdavis** [comment]
I've gone with `Total study time on this part of the test bank` for now. 

(I may amend later if I think of something better!)

Feel free to edit.
