### ISSUE TITLE
Time incorrect on individual session result sidebar

### ISSUE THREAD

**Issue by nickdavis** [nickdavis/cmaexamacademy.com#2]
![session result time calculation](https://user-images.githubusercontent.com/1030574/66044962-a0ba8700-e51a-11e9-8aef-f82b8e3affd2.png)

> Please have a look at total time taken. It should be 1.39x50qs which is equal to 69 mins appx. But it is mentioned 22.52.

From student (s.abbasmadani at gmail dot com), via Nathan (1 Oct 2019)

**Comment by nickdavis** [comment]
I looked into this, turns out the total time was not showing the hour count, only minutes and seconds. So `22:52` (minutes/seconds) was appearing instead of `01:22:52`(hours/minutes/seconds).

The average time was always correct, but the wrong total time showing made it appear that it wasn't.

**Comment by nickdavis** [comment]
Pushed to live site

**Comment by cmaexamacademy** [comment]
@nickdavis I think this issue is still happening in the Analytics page header and body, as well as in Review. Can you please fix it?

**Comment by cmaexamacademy** [comment]
On the Analytics page, please review MCQs and Essays. Thanks

**Comment by nickdavis** [comment]
@cmaexamacademy Analytics uses `Hours Studied` (hh:mm, as per the design) rather than `Total Time` (hh:mm:ss) which is what is used in the Session result sidebar and was what had the issue

I also checked and bumped my total study time past 24 hours and it carried on showing them correctly in Analytics (showing 25 hours, rather than losing the extra hours beyond one day). See screenshot below.

<img width="234" alt="Screenshot 2019-10-04 at 13 29 41" src="https://user-images.githubusercontent.com/1030574/66207593-0e95b880-e6ab-11e9-95a9-5696195527e4.png">

So I think this is OK. I'll check Review though.

**Comment by nickdavis** [comment]
OK, on **Review**, I've now tweaked to show `hh:mm:ss` so it's consistent with the individual Session result screen.

<img width="846" alt="Screenshot 2019-10-04 at 13 47 28" src="https://user-images.githubusercontent.com/1030574/66208663-8f55b400-e6ad-11e9-8c01-e923d82d29d6.png">

**Comment by nickdavis** [comment]
@cmaexamacademy closing this as I believe this is resolved, but please do re-open if you would like any further tweaks.

**Comment by cmaexamacademy** [comment]
@nickdavis so total hours studied. How is this calculated? Mine shows over 20 hours but I haven't taken practice exams for that long. 
<img width="497" alt="Screen Shot 2019-10-04 at 12 31 03 PM" src="https://user-images.githubusercontent.com/56087053/66234641-0f2a5100-e6a3-11e9-81ed-6b7f35fa4fc7.png">

**Comment by nickdavis** [comment]
@cmaexamacademy 

It's based on total session time. If you've been testing it a lot (as we have been) and left a session open in a tab and then a few hours later come back to the session again and answered another question (without having saved and exited the session first) then you could easily hit that time.

I checked my raw session data vs what it was showing on Friday and it was correct. The issue we had before was not showing the hour count in certain parts of the site, rather than not adding up correctly.

If you want, I can go through your raw session data and double check your calculation too. Otherwise I think we can close this.

**Comment by cmaexamacademy** [comment]
Nick, could you check mine and make sure it adds up correctly? Thank you 

Thank you,

Nathan Liao, CMA | CMA Coach
www.cmaexamacademy.com
PO BOX 124575
San Diego, CA 92112

--- original message ---
> Sun, Oct 6 at 3:33 PM, <notifications@github.com> wrote:


> @cmaexamacademy

> It's based on total session time. If you've been testing it a lot (as we have been) and left a session open in a tab and then a few hours later come back to the session again and answered another question (without having saved and exited the session first) then you could easily hit that time.

> I checked my raw session data vs what it was showing on Friday and it was correct. The issue we had before was not showing the hour count in certain parts of the site, rather than not adding up correctly.

> If you want, I can go through your raw session data and double check your calculation too. Otherwise I think we can close this.

> —

> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by nickdavis** [comment]
As we're talking a computer crunching raw data, it adds up, as you'd expect.

In terms of the make up of that data, you had one Essay Problem session which was 26 hours (must've been a tab left open and then resumed again the next day or the day after), must've been when we were testing them.

<img width="838" alt="Screenshot 2019-10-07 at 12 26 48" src="https://user-images.githubusercontent.com/1030574/66307989-d6d27f00-e8fd-11e9-93ab-57755ffde2af.png">

---

There is a disparity at the moment though in terms of how we're presenting things on the Analytics page.

- `Hours Studied` (at the top): is all Sessions added together from start to finish (whether you were answering a question, reviewing an answer etc etc).
- `Total Hours` (per table row): is the total time spent on all Questions in that Section / Topic

But the second calculation (`Total Hours`), as we've previously discussed, only includes time when 'pondering' a question (i.e. not on the 'answer' view). `Hours Studied` records everything while a Session is open from start to finish.

However if a student quickly totals up their `Total Hours` in the table rows they will likely see that it doesn't match `Hours Studied`. Therefore it is probably best to use the same calculation for Total Hours for consistency and to avoid confusion.

I will look at that next.

**Comment by nickdavis** [comment]
OK, `Hours Studied`, in the Analytics top section now uses the same calculation method as the `Total Hours` column in the table below, making everything consistent.

There is only one thing we might want to tweak further, up to you.

At the moment, whether you're on the MCQs tab or the Essays tab, `Hours Studied` is total time across both tabs. So, in your case you have `5h 22m` total, with `5h 13m` on MCQs and 8m on Essay Problems. (You've got another minute in there but it doesn't show because our cut off for showing time, per topic is at least one minute).

**However, if you would prefer the `Hours Studied` to change to reflect only the time spent on the current tab's questions then re-open this, let me know and I will tweak it.**

(At the moment, my thinking is everything above the MCQ / Essay tabs, e.g. Exam Ready, is global. Everything below the tabs is just related to that Exercise Type so maybe that is one reason to leave as is).

**Comment by cmaexamacademy** [comment]
@nickdavis header info should be global, I agree. Below it should be specific to each exercise type. 
 
I noticed that my total hours dropped considerably from 26 down to 5. What happened? I thought 26 was correct? 
<img width="988" alt="Screen Shot 2019-10-07 at 12 18 17 PM" src="https://user-images.githubusercontent.com/56087053/66342087-77746f00-e8fd-11e9-93bd-c6d7e6024acc.png">

When I go to the Essay report, I don't see 26 hours anywhere. So I don't know how it's showing 26 hours of one essay scenario on your end.

**Comment by cmaexamacademy** [comment]
@nickdavis about your comment below, I agree. let's make it all consistent. 

 "But the second calculation (Total Hours), as we've previously discussed, only includes time when 'pondering' a question (i.e. not on the 'answer' view). Hours Studied records everything while a Session is open from start to finish.

However if a student quickly totals up their Total Hours in the table rows they will likely see that it doesn't match Hours Studied. Therefore it is probably best to use the same calculation for Total Hours for consistency and to avoid confusion."

**Comment by nickdavis** [comment]
> When I go to the Essay report, I don't see 26 hours anywhere. So I don't know how it's showing 26 hours of one essay scenario on your end.

Look under Review for Part 1, there is one particular Session (shown in my screenshot) with the 26 hours

**Comment by nickdavis** [comment]
> I noticed that my total hours dropped considerably from 26 down to 5. What happened? I thought 26 was correct?

Because we changed the calculation as described above. In short:
- `Review` screen shows (individual) Session times
- `Analytics` screen shows total Question (but not Answer) times

Previously we were mixing total session times _and_ question times on Analytics.

Hope that makes sense, if not let's discuss.

**Comment by nickdavis** [comment]
Following our discussion yesterday (7 Oct), I've now switched to using Total time (`hh:mm:ss`) on Analytics too, for consistency with other parts of the test bank. (Previously was `hh:mm`).

<img width="235" alt="Screenshot 2019-10-08 at 11 22 50" src="https://user-images.githubusercontent.com/1030574/66388421-ffba4900-e9bd-11e9-880b-975ed2131a2d.png">

<img width="97" alt="Screenshot 2019-10-08 at 11 22 57" src="https://user-images.githubusercontent.com/1030574/66388424-021ca300-e9be-11e9-9db2-d01398192676.png">
