### ISSUE TITLE
Automatic Scroll Down Issue

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#22]
@nickdavis When I click on the Practice buttons at the top, the screen scrolls down but the spot it stops isn't ideal. The first screenshot is where it stops. The second screeshot shows where it should stop. 
<img width="980" alt="Screen Shot 2019-10-07 at 12 07 45 PM" src="https://user-images.githubusercontent.com/56087053/66340974-295e6c00-e8fb-11e9-8299-0841baad3dc5.png">

<img width="1010" alt="Screen Shot 2019-10-07 at 12 07 53 PM" src="https://user-images.githubusercontent.com/56087053/66340987-2f544d00-e8fb-11e9-92db-ef1febe42921.png">

**Comment by nickdavis** [comment]
This is due to the fact that - after the merge with the theme header last week - we now keep the header in view on scroll.

I will re-work this to offset the difference in height.

**Comment by nickdavis** [comment]
Fixed (via commit https://github.com/nickdavis/cmaexamacademy.com/commit/3452b294c9b5357b8edd7bf9bc4c6eabc4b4daea)
