### ISSUE TITLE
Essay Skip button Issue

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#23]
@nickdavis  a student said this "I skipped one essay question and it ended the entire essay test and gave me result. So I guess we can't skip one individual question from an essay test, we have to leave it blank without clicking flag/skip to continue the test."

I ran an essay scenario with 2 essays to test this out. When I got to the first questions tab, I click on Skip thinking it would take me to the next question in that same Essay, but instead it took me to the 2nd Essay scenario. When I clicked Skip on a question in the 2nd Essay Scenario, instead of taking me to the next question, it ended the practice exam altogether. I went back to the dashboard to see if it had saved it so I could resume, it wasn't there. So it did effectively terminate the exam.

**Comment by nickdavis** [comment]
@cmaexamacademy 

We discussed this a while back. Looking purely at a multiple Essay Problem session:

- `Skip` skips the whole of the current Essay Problem exercise
- `Next` takes you to the next Tab within that Exercise

Instead, if `Skip` just took you to the next tab, it would be. doing the same thing as `Next` on most tabs (i.e. two buttons doing the same thing).

We could just remove `Skip` then, but it is a useful function to be able to skip a whole Exercise (without having to click Next / Next / Next or the last tab and then Submit), so perhaps the simple answer is to re-name it to **Skip Exercise (?) / Question(?)** if it's not clear in it's current guise?

**Comment by nickdavis** [comment]
Note to self change to Skip Exercise

**Comment by cmaexamacademy** [comment]
@nickdavis change it to "Skip Scenario"

**Comment by nickdavis** [comment]
Hide Skip button on final Essay Scenario

**Comment by nickdavis** [comment]
The text change - Skip Scenario - is done and pushed to the live site

**Comment by nickdavis** [comment]
> Hide Skip button on final Essay Scenario

This is now done too
