### ISSUE TITLE
Number of Attempts

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#28]
@nickdavis I got this screenshot from a student. The number of attempts is the number of exams ran for this section/topic? or what is it? Seems so high. 
<img width="797" alt="Screen Shot 2019-10-11 at 3 24 38 PM" src="https://user-images.githubusercontent.com/56087053/66688418-5da79480-ec3b-11e9-9dbc-268b1617f4a4.png">

**Comment by nickdavis** [comment]
@cmaexamacademy, as per our tooltip text:

> the total number of **question** attempts for a particular section and/or topic

So `Attempts` will almost always be higher than the total of the `Correct` / `Incorrect` columns, which only refers to the last **attempt** for each particular question.

Therefore `Correct` / `Incorrect` can never exceed the `Total` column, whereas a student could make an infinite number of **total** `Attempts` on the questions in any particular topic / section.

(Equally `Total Time` is the total time of all question attempts).

**Comment by nickdavis** [comment]
Removing `bug` label and closing. Please re-open if you believe there is an issue.

**Comment by cmaexamacademy** [comment]
@nickdavis this metric is confusing people, so my first instinct is to hide for now. Is it possible to hide this from Analytics?

**Comment by nickdavis** [comment]
Will do

**Comment by nickdavis** [comment]
Done and pushed to live
