### ISSUE TITLE
Copy Questions

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#40]
Hey @nickdavis, is there a way to copy questions instead of having to always create them from scratch? It would save us a lot of time on data entry.

**Comment by nickdavis** [comment]
@cmaexamacademy 

Absolutely. You have a plugin installed (Duplicate Post) which offers this functionality already, I've enabled the option for the Clone feature to work with TB. Questions as well. See screenshot below for how to access it.

<img width="392" alt="Screenshot 2019-10-18 at 11 06 08" src="https://user-images.githubusercontent.com/1030574/67085774-5c282000-f197-11e9-8fd5-f51878c9630e.png">

I've done a quick test and it seems to copy all the relevant data across too.

**Comment by cmaexamacademy** [comment]
@nickdavis perfect thank you .
