### ISSUE TITLE
Reporting Bugs Form

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#41]
@nickdavis not sure if you'd consider this a "bug" or not, but is there a way for people to click on a button inside each MCQ where students will click if they need more help understanding the question and it would open a form where they could type in their questions and it would also retrieve the question number automatically? This will help with bugs as well. I keep asking people to take screenshots of the issue and include the question, session but there are just too many steps for them to do and don't ever get back to me. 

So this could be a much easier way for them to send what they need to us to troubleshoot. Thoughts?

**Comment by nickdavis** [comment]
Initial thoughts: we have a report bug / issue link in the corner of each question (within a session), that links to a form.

The form should be able to automatically pull the current session and question ids and - when submitted - could be set to be sent to you (or your team automatically). We'd also have a separate field where they could submit any comments.

From there you can decide to escalate as necessary.

**Comment by cmaexamacademy** [comment]
@nickdavis we do? I don't see a link in the corner of each question inside a practice exam. Can you show me a screenshot of where it's supposed to be? 

The form can be sent to questions@cmacoach.com and including a comment field would be great so they can explain what the issue with the question is.

**Comment by nickdavis** [comment]
> @nickdavis we do? I don't see a link in the corner of each question inside a practice exam. Can you show me a screenshot of where it's supposed to be?

@cmaexamacademy no, I meant initial thoughts on a solution, i.e. we _could_ have.

I'll take a look at this and let you know.

**Comment by cmaexamacademy** [comment]
@nickdavis oh ok I misunderstood. Thank you

**Comment by nickdavis** [comment]
@cmaexamacademy 

I've added this to `staging1` so you can take a look first.

If you start any session you should see the Report A Problem button in the bottom left.

<img width="890" alt="Screenshot 2019-10-22 at 23 36 58" src="https://user-images.githubusercontent.com/1030574/67340317-00f28680-f525-11e9-8f56-dfd4eb20aac8.png">

Clicking this takes you to a separate Feedback page (in a new tab), which also passes on the current session id and other details as hidden fields which are then submitted to questions@cmacoach.com when the form is submitted, along with the user's message.

<img width="668" alt="Screenshot 2019-10-22 at 23 28 46" src="https://user-images.githubusercontent.com/1030574/67342956-9bee5f00-f52b-11e9-8e71-6f77234dd4ba.png">

(I could potentially re-visit this as modal pop-up later on but I wanted to get something out there ASAP).

Let me know if you're happy for me to move it to the live site.

**Comment by cmaexamacademy** [comment]
@nickdavis can you update the title of the form to Test Bank Feedback

Is it possible to include a Upload function so people who want to include a screenshot can?

**Comment by nickdavis** [comment]
Yes, I’ll do both and let you know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nickdavis** [comment]
@cmaexamacademy these changes have been made and this has been pushed up to the live site

**Comment by cmaexamacademy** [comment]
@nickdavis After a form is submitted, can you update this message "Thank you for your message. It has been sent." to include "Please close this browser window."

Also I attached an image but it wasn't included in the email I got.

**Comment by nickdavis** [comment]
@cmaexamacademy, both done.

<img width="693" alt="Screenshot 2019-10-26 at 10 12 46" src="https://user-images.githubusercontent.com/1030574/67622107-039bf700-f817-11e9-8851-e08b6a4a44c7.png">

The uploaded file is now included as a file attachment in the email that is sent by the contact form.

<img width="626" alt="Screenshot 2019-10-26 at 17 32 02" src="https://user-images.githubusercontent.com/1030574/67622112-1ca4a800-f817-11e9-80b1-11b1184a48e2.png">
