### ISSUE TITLE
Correct % Circle

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#42]
Hey @nickdavis just dropping this here to remind us to add this circle with the % in it. We need this in the main dashboard and in Analytics too. Thanks 

<img width="599" alt="Screen Shot 2019-10-18 at 11 30 46 AM" src="https://user-images.githubusercontent.com/56087053/67118919-d017f780-f19a-11e9-9038-dd02b416533c.png">

**Comment by nickdavis** [comment]
No problem, will do

**Comment by nickdavis** [comment]
Done
