### ISSUE TITLE
Preview Questions

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#43]
Hi @nickdavis, is there a way to preview from the editor how a question and answer is going to look in the test bank? We are getting feedback that questions with tables don't look good at all. Some examples attached. It'd be very helpful to be able to preview the questions so we know how they'll look in the test bank. 

![Screenshot (1715)](https://user-images.githubusercontent.com/56087053/67325405-f656d380-f4c9-11e9-9d06-3587679109b3.png)
![Screenshot (1758)](https://user-images.githubusercontent.com/56087053/67325406-f656d380-f4c9-11e9-8a5d-11d73f1eee16.png)
![Screenshot (1713)](https://user-images.githubusercontent.com/56087053/67325407-f6ef6a00-f4c9-11e9-8223-0db0040d2ba9.png)

**Comment by nickdavis** [comment]
Yes, I can see why this might be beneficial.

I can probably build something for this, but it may take a little while. At the moment, questions only exist on the front end as part of a session (which in turn part is part of a test bank). Unlike blog posts they don't exist on their own, with their own URL, so I'd need to do something a little different.

I'll take a look and get back to you.

**Comment by nickdavis** [comment]
I’ve got this mostly working. Will let you know when it’s ready to test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nickdavis** [comment]
@cmaexamacademy, administrators and Editors can now view or preview (if not yet published) Test Bank questions. For example, see the following URL, if logged in.

https://cmaexamacademy.com/tb-question/p2sc1-essay-07-mcq-03/

I've also included the option to see the question in the answered view via the `Show Answer` button at the bottom of the front end view.

**Comment by nickdavis** [comment]
To view a question just find it in the admin and either click any of the links shown below.

<img width="934" alt="Screenshot 2019-10-25 at 21 46 13" src="https://user-images.githubusercontent.com/1030574/67599726-f2001400-f770-11e9-942d-9986d729dc85.png">
<img width="213" alt="Screenshot 2019-10-25 at 21 45 25" src="https://user-images.githubusercontent.com/1030574/67599728-f2001400-f770-11e9-9c1c-c8ffba7e1b49.png">

**Comment by cmaexamacademy** [comment]
@nickdavis thanks so much! This is going to be super helpful
