### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#6]
Beta testers have said that the font size is too small to read. Wonder if there's a way to increase it for the entire test bank?

**Comment by nickdavis** [comment]
Yeah, I agree, it's very small, but follows the design in that respect at the moment.

I'll start by bumping the question / answer text, as those seem to be the worst offenders and if you want to bump anything else after that we can revisit.

**Comment by nickdavis** [comment]
I've increased the Question and Answer text font sizes by 1 unit, see screenshots below (but probably best if you try it for yourself), and pushed to the live site.

<img width="872" alt="Screenshot 2019-10-03 at 12 30 18" src="https://user-images.githubusercontent.com/1030574/66123520-294c2c80-e5da-11e9-8343-f9b9cb263462.png">

<img width="845" alt="Screenshot 2019-10-03 at 12 30 51" src="https://user-images.githubusercontent.com/1030574/66123530-30733a80-e5da-11e9-9dfb-2fff698f7fdf.png">

@cmaexamacademy I'll close this for now, but if you want any further tweaks, just reply below and we'll re-open this issue.
