### ISSUE TITLE
Add transition (and fail?) state to Flagged button

### ISSUE THREAD

**Issue by nickdavis** [nickdavis/cmaexamacademy.com#7]

**Comment by nickdavis** [comment]
As discussed, added a subtle fade effect to the flagged button when clicked to represent that something is happening (fade effect stops when server updates the flagged status).

Depending on the speed of the server at the time, you may not notice it straight away, but when your connection to the server is a little bit slower you will see the effect.

Pushed to live site.

**Comment by cmaexamacademy** [comment]
@nickdavis one user (lavanecueva@gmail.com) is reporting the following issues:

"I flagged a question but, I did not see it  in the final review"
"I answered a question but the system did not marked my answer."

**Comment by nickdavis** [comment]
> "I flagged a question but, I did not see it in the final review"
@cmaexamacademy - We don't show them in the final session results yet. That will be take care of by #36 (let me know if that's a priority)

**Comment by nickdavis** [comment]
> "I answered a question but the system did not marked my answer."

This is a separate issue (and we also need more information). Moved to #38

<img width="873" alt="Screenshot 2019-10-15 at 10 43 26" src="https://user-images.githubusercontent.com/1030574/66820729-2423a180-ef39-11e9-99c8-b667c204d766.png">


I need to know which session and which question.
